[package]
name = "hangups"
version = "0.0.1"
authors = ["MTRNord"]

[dependencies]
hyper = { git = "https://github.com/hyperium/hyper" }
protobuf = "1.2.2"
rand = "0.3"
sha1 = "0.2.0"
rustc-serialize = "0.3.23"
jconfig = "0.1.0"
regex = "0.2"
url = "1.4.0"
tokio-core = "0.1.6"
futures = "0.1.13"
